name: Convert version.txt to version.json

on:
  push:
    branches:
      - main # update if your default branch is different
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version.txt and write version.json
        run: |
          VERSION=$(cat version.txt | tr -d '\n')
          echo "{ \"version\": \"$VERSION\" }" > version.json

      - name: Commit and push version.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.json
          git commit -m "chore: update version.json from version.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
